# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tomer Weller / Blob
email: tomer.weller@gmail.com
description: "an indeterminate mass or shape"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blob.tomerweller.com" # the base hostname & protocol for your site
twitter_username: tomerweller
github_username:  tomerweller

# Build settings
markdown: kramdown